[profile.default]
optimizer = true
optimizer_runs = 20_000
src = "src"
out = "out"
libs = ["lib"]
script = 'script'
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]
[rpc_endpoints]
alys_testnet = "${RPC_URL}"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
